# Generated by Django 3.2.19 on 2023-07-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20230320_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(max_length=42, null=True),
        ),
    ]
