# Generated by Django 3.2.23 on 2024-03-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="notification_limit",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
