# Generated by Django 3.2.18 on 2023-03-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartcontract',
            name='network',
            field=models.CharField(choices=[('MAINNET', 'mainnet'), ('SEPOLIA', 'sepolia'), ('GOERLI', 'goerli')], default='MAINNET', max_length=100),
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='chain',
            field=models.CharField(choices=[('ETH', 'eth'), ('BSC', 'bsc'), ('POLYGON', 'polygon')], max_length=16),
        ),
    ]
