# Generated by Django 3.2.16 on 2023-02-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcontract',
            name='chain',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
