# Generated by Django 3.2.18 on 2023-03-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontract', '0002_auto_20230307_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcontract',
            name='chain',
            field=models.CharField(choices=[('ETH', 'eth')], max_length=16),
        ),
    ]
