# Generated by Django 3.2.19 on 2023-07-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontract', '0005_alter_smartcontract_abi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcontract',
            name='address',
            field=models.CharField(max_length=42),
        ),
    ]
