# Generated by Django 3.2.19 on 2023-07-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontract', '0006_alter_smartcontract_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartcontract',
            name='object_type',
            field=models.CharField(choices=[('CONTRACT', 'contract'), ('WALLET', 'wallet')], default='CONTRACT', max_length=8),
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='chain',
            field=models.CharField(choices=[('ETH', 'eth'), ('FLOW', 'flow')], max_length=16),
        ),
    ]
