# Generated by Django 3.2.19 on 2023-07-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontract', '0007_auto_20230711_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcontract',
            name='object_type',
            field=models.CharField(choices=[('CONTRACT', 'contract'), ('ACCOUNT', 'account')], default='CONTRACT', max_length=8),
        ),
    ]
