# Generated by Django 3.2.19 on 2023-07-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcontract', '0008_alter_smartcontract_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcontract',
            name='network',
            field=models.CharField(choices=[('MAINNET', 'mainnet'), ('TESTNET', 'testnet'), ('SEPOLIA', 'sepolia'), ('GOERLI', 'goerli')], default='MAINNET', max_length=100),
        ),
    ]
