version: '3.8'

services:
   backend:
    container_name: backend_demo_app_third_eye
    expose:
      - "8000"
    image: ghcr.io/thirdeye-dev/thirdeye:latest
    entrypoint: docker/entrypoint/entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - ../db.sqlite:/app/backend/db.sqlite
    env_file:
      - ./.env
    environment:
      - DEMO_INSTANCE=true
  