blockchain_alerts:
  - alert_type: "every_transaction"
    alerts:
      nameA:
        attribute: "{{ $transaction.gas }}"
        operator: ">="
        value: 100000
        notifications:
          - send_email
          - send_sms