blockchain_alerts:
  - blockchain_name: "Ethereum"
    network: "mainnet"
    alert_type: "every_transaction"
    contract_addresses: ["0x1234567890abcdef1234567890abcdef12345678"]
    alerts:
      nameA:
        attribute: "{{ $transaction.gas }}"
        operator: ">="
        value: 100001
        notifications:
          - send_email
          - send_sms