# Generated by Django 3.2.16 on 2023-03-06 23:29

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import api_app.monitoring.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("smartcontract", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="IoC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ioc_type", models.CharField(choices=[], max_length=120)),
                ("threshold", models.FloatField(null=True)),
                (
                    "threshold_currency",
                    models.CharField(
                        choices=[("ETH", "Eth"), ("GWEI", "Gwei"), ("USD", "Usd")],
                        max_length=16,
                    ),
                ),
                (
                    "alert_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=16),
                        default=list,
                        size=None,
                        validators=[api_app.monitoring.models.validate_alert_type],
                    ),
                ),
                ("alert_url", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "SmartContract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smartcontract.smartcontract",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonitoringTasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=255, null=True)),
                ("task_status", models.CharField(blank=True, max_length=16, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "SmartContract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smartcontract.smartcontract",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IOCAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILURE", "Failure")],
                        max_length=16,
                    ),
                ),
                ("url", models.CharField(max_length=255, null=True)),
                ("request_token", models.CharField(max_length=16, null=True)),
                ("response", models.TextField(blank=True, null=True)),
                ("response_code", models.IntegerField(blank=True, null=True)),
                ("email", models.CharField(max_length=255, null=True)),
                ("phone_number", models.CharField(max_length=255, null=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ioc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="monitoring.ioc"
                    ),
                ),
            ],
        ),
    ]
