# Generated by Django 3.2.18 on 2023-03-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringtasks',
            name='task_status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=16),
        ),
    ]
