# Generated by Django 3.2.18 on 2023-03-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_auto_20230325_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringtasks',
            name='task_status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('PENDING', 'Pending'), ('FAILURE', 'Failure'), ('STOPPED', 'Stopped')], default='PENDING', max_length=16),
        ),
    ]
