# Generated by Django 3.2.18 on 2023-03-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0005_alter_monitoringtasks_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoringtasks",
            name="task_status",
            field=models.CharField(
                choices=[
                    ("RUNNING", "Running"),
                    ("PENDING", "Pending"),
                    ("STOPPED", "Stopped"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
