name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - flow
    paths:
      - '**.py'
      - '**.sh'

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker backend image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/Dockerfile
        push: true
        tags: ghcr.io/thirdeye-dev/thirdeye:${{ env.BRANCH_NAME }}

    - name: Build and push Docker flow support image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: flowSupport/Dockerfile
        push: true
        tags: ghcr.io/thirdeye-dev/thirdeye:flowsupport_${{ env.BRANCH_NAME }}
      
