name: Build and Push Docker Images

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - '**.sh'
      - 'docker/Dockerfile.*'
      - '**.yml'

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker backend image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/Dockerfile.backend
        push: true
        tags: ghcr.io/thirdeye-dev/thirdeye:latest

    # - name: Build and push Docker frontend image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: ..
    #     file: docker/Dockerfile.frontend
    #     push: true
    #     tags: ghcr.io/thirdeye-dev/thirdeye-frontend:latest
