name: Deploy to server

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      env:
        PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.SERVER_SSH_HOST }}

      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa ${HOST} >> ~/.ssh/known_hosts

    - name: Deploy to server
      env:
        PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        DEPLOY_USER: ${{ secrets.SERVER_SSH_USER }}
        HOST: ${{ secrets.SERVER_SSH_HOST }}
        CODE_PATH: ${{ vars.CODE_PATH }}
      run: |
        ssh -i ~/.ssh/id_rsa ${DEPLOY_USER}@${HOST} "/home/deployuser/thirdeye/docker/cicd.sh"
