name: Black Formatting

on: [push, pull_request]

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Check formatting
      run: black --check .

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Fix black formatting issues (${{ github.sha }})"
        body: "This pull request fixes formatting issues detected by black on commit ${{ github.sha }}."
        branch: fix-black-formatting-${{ github.sha }}
        commit-message: "Fix black formatting issues (${{ github.sha }})"
