name: Generate OpenAPI Schema for Redoc
on:
  push:
    branches:
      - master
      - test

jobs:
  generate-schema:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/run-requirements.txt

      # this edtion of the workflow uses Django's inbuilt generateschema to give us the schema file
      - name: Generate the schema file
        run: |
          ./backend/manage.py spectacular --file docs/schema.yml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "generate-openapi-schema"
          title: "🤖 Generate OpenAPI schema for Redoc"
          body: |
            This PR generates the OpenAPI schema file for Redoc. It was generated automatically by a GitHub Actions workflow.

          commit-message: "🤖 Generate OpenAPI schema for Redoc"
          delete-branch: true
          labels: "auto-generated"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
